site_name: End to End ML pipeline for profiling insurance customers
# 
site_author: XRD Group
# 

theme:
  name: material

nav:
  - Home: index.md
  - API Reference:
    - $api/policyML.***
  - Notebooks: 
    - notebooks/model_experiments.ipynb
    - notebooks/gold_tables.ipynb
    - notebooks/data_explore.ipynb


plugins: 
  - search
  - mkdocs-jupyter
  - mkapi
